\ir sql/supplemental_functions/01-create-mpartman-schema.sql
\ir sql/supplemental_functions/02-partitioned-tables-views.sql
\ir sql/supplemental_functions/f_grant_table_privileges.sql
\ir sql/supplemental_functions/f_set_part_name.sql
\ir sql/supplemental_functions/f_is_eligible.sql
\ir sql/supplemental_functions/f_get_minvalue_part_name.sql
\ir sql/supplemental_functions/f_grant_package_privileges.sql
\ir sql/supplemental_functions/f_subp_is_eligible.sql
\ir sql/supplemental_functions/f_get_part_column.sql
\ir sql/supplemental_functions/f_is_eligible_for_detach.sql
\ir sql/supplemental_functions/f_get_hash_part_by_value.sql
\ir sql/supplemental_functions/f_get_part_by_value.sql
\ir sql/supplemental_functions/f_set_config.sql
\ir sql/supplemental_functions/f_get_min_max_value_range.sql
\ir sql/supplemental_functions/f_add_interval.sql
\ir sql/supplemental_functions/f_get_maxvalue_part_name.sql
\ir sql/supplemental_functions/f_has_default_part.sql
\ir sql/supplemental_functions/f_default_part_has_data.sql
\ir sql/supplemental_functions/f_set_schema.sql
\ir sql/supplemental_functions/f_get_allowed_types.sql
\ir sql/supplemental_functions/f_get_min_max_value_list.sql
\ir sql/supplemental_functions/f_get_default_part_name.sql
\ir sql/supplemental_functions/f_get_range_bvalue.sql
\ir sql/supplemental_functions/f_get_overlap_by_range.sql
\ir sql/public_functions/f_range_add_interval_partitions_2.sql
\ir sql/public_functions/f_list_add_partitions.sql
\ir sql/public_functions/f_range_add_interval_partitions_1.sql
\ir sql/public_functions/f_detach_part.sql
\ir sql/public_functions/f_range_merge_partitions.sql
\ir sql/public_functions/f_do_retention.sql
\ir sql/public_functions/f_find_part_by_value_1.sql
\ir sql/public_functions/f_find_part_by_value_2.sql
\ir sql/public_functions/f_list_split_partition.sql
\ir sql/public_functions/f_drop_part.sql
\ir sql/public_functions/f_check_gap_range.sql
\ir sql/public_functions/f_list_add_interval_partitions.sql
\ir sql/public_functions/f_range_add_partitions.sql
\ir sql/public_functions/f_list_merge_partitions.sql
\ir sql/public_functions/f_get_all_part_info.sql
\ir sql/public_functions/f_range_split_partition.sql

