create table if not exists :testschema.tb_list_decimal (
	id bigint not null generated by default as identity,
	type_decimal decimal(27,10)
)
PARTITION BY list (type_decimal);

create table :testschema.tb_list_decimal_p_default PARTITION OF :testschema.tb_list_decimal default;

insert into :testschema.tb_list_decimal(type_decimal)
select s from generate_series(50.347, 80, 7.541) as t(s);

create table if not exists :testschema.tb_list_text (
	id bigint not null generated by default as identity,
	type_text text
)
PARTITION BY list (type_text);

create table :testschema.tb_list_text_p_default PARTITION OF :testschema.tb_list_text default;

