create table if not exists :testschema.tb_hash_bigint (
	id bigint not null generated by default as identity,
	type_bigint bigint
)
PARTITION BY hash (type_bigint);

create table :testschema.tb_hash_bigint_p_1 PARTITION OF :testschema.tb_hash_bigint for values with (modulus 3, remainder 0);
create table :testschema.tb_hash_bigint_p_2 PARTITION OF :testschema.tb_hash_bigint for values with (modulus 3, remainder 1);
create table :testschema.tb_hash_bigint_p_3 PARTITION OF :testschema.tb_hash_bigint for values with (modulus 3, remainder 2);

insert into :testschema.tb_hash_bigint(type_bigint)
select s from generate_series(1, 100) as t(s);

